### ISSUE TITLE
Add `explicit-types` rule

### ISSUE THREAD

**Issue by fvictorio** [solhint-community/solhint-community#10]
Copying my issue from https://github.com/protofire/solhint/issues/387

---

### Summary

Add a new `explicit-types` rule to forbid or enforce explicit types (like `uint256`) that have an alias (like `uint`). This rule should implement the auto-fix mechanism.

### Motivation
Prettier Solidity used to have an option to do this, but it was removed in v1.0.0 because we felt that that kind of thing belongs to a linter rather than a formatter.

### Details
The rule should accept an options object `{ default: "explicit" | "implicit" }`, where "explicit" means that `uint256`, `int256`, etc. should be used and "implicit" means that `uint`, `int`, etc. should be used. The default should be "explicit".

The types that should be affected are:
- `uint256` and `uint`
- `int256` and `int`
- `ufixed128x18` and `ufixed`
- `fixed128x18` and `fixed`

I'm intentionally not including `bytes1` and `byte`. The reason is that, since we don't have version information, we can't know if an instance of `bytes1` (with the implicit default selected) is an error or not. If there's demand for this, we might consider adding a new option to the rule.

**Comment by fvictorio** [comment]
I might have this weekend to implement this, although I've learned to not make those kind of promises. But maybe!

**Comment by juanpcapurro** [comment]
this was implemented on protofire/solhint and then I backported it on #41 , although inmediately afterwards I chose to remove the option and make the default behaviour the only one. If you think there are projects that might want to use *only* the implicit variants then I could bring the option back, otherwise feel free to close this

**Comment by fvictorio** [comment]
I'm always in favor of removing options.
