### ISSUE TITLE
absorb defi-wonderland/solhint-plugin features

### ISSUE THREAD

**Issue by juanpcapurro** [solhint-community/solhint-community#113]
The goal of this issue is to discuss the best way to include features defined in defi-wonderland's plugin in a way that doesn't make adoption by users of protofire/solhint significantly harder.

## `contract-data-order`
**status:** nothing done yet, feedback needed

I think the behaviour of this rule could be part of `ordering`. Adding that
would be a small breaking change, but it's the perfect opportunity to do so
since I'm finalizing the spec for `4.0.0`.

however, I'd like to consider a small change: only enforce constants are
above all other variables, since that'd **never** get in the way of storage layout
optimizations, where someone might squeeze an immutable address and a few
mutable timestamps/bitmasks together for all of them to fit in a single storage
slot. Then this behaviour can even be made part of the 'recommended' ruleset.

If that's a tough sell, then I could add the rule as-is but I'd be reticent to
making it recommended

part of this (enums vs struct ordering) is tracked in #112

## `interface-member-order`
**status:** nothing done yet, feedback needed

This one is a bit more problematic than the above since the ordering defined by
it **contradicts** rather than _refines_ the behaviour of `ordering`, which
requires:

1. struct/enums (doesnt care about order, #112)
1. events
1. errors

while this rule requires:

1. events
1. errors
1. enums
1. structs

While I agree that it makes perfect sense to have structs at the bottom since
they are usually the hardest definitions to read (of those four), adding that
change to `ordering`, one of the least controversial rules, would be the biggest
hurdle for users to migrate to this repository, since they'd have to re-order
their contracts (I guess I could make a fixer to make it easier tho, but the
fixer itself would be hard to implement).

would it be an okay compromise if `ordering` enforced the following instead? 

1. enums
1. structs
1. events
1. errors

other alternatives would be:
- making it a separate rule which contradicts `ordering`
- making interface ordering different than for regular contracts, so this
breaking change would have a smaller impact

I'm open to input on this

## `non-state-vars-leading-underscore` 
**status:** nothing done yet, to be included (#114)

I believe this is a completely valid naming convention, although it'd contradict
`private-vars-leading-underscore` and the style guide. It wouldn't be in
`solhint:recommended`, but that's it.

## `wonder-var-name-mixedcase`
**status:** nothing done yet, NOT to be included

I'm not sure I understand how this contradicts `var-name-mixedcase`, since the
latter disallows mutable variables in CapWords and snake_case, uppercase or not.

I believe this rule was created in the timespan where protofire/solhint was
unmantained and didn't skip immutable/constant variables in
`var-name-mixedcase`, so now it's obsolete. Please confirm this 🙃 

also, bear in mind now `{immutable,constant}-name-snakecase` are now in the
recommended ruleset so this naming convention should be less of an issue.

## `struct-name-camelcase` 
**status:** covered by #109

## `enum-name-camelcase` 
**status:** covered by #109

## `immutable-name-snakecase` 
**status:** ported by protofire before the fork
re-implemented

aside: we also have `const-name-snakecase`. Do you think they should be merged?

## `import-statement-format` 
**status:** re-implemented as `no-global-import`

## `interface-starts-with-i` 
**status:** backported in #107

## `named-return-values` 
**status:** re-implemented/copied by protofire and backported in #56

**Comment by gas1cent** [comment]
Hey @juanpcapurro, great effort! ❤️ Let me try to address some of the questions.

## `contract-data-order`
Totally agree that it would be a nice addition to the `ordering` rule. If I'm not misinterpreting the suggestion, the rule should never get into the way of optimizations because constants and immutable variables are not stored in the state, rather they're a part of the contract's bytecode. Hence it only makes sense to declare them all together for readability reasons.

## interface-member-order
Let me check this with the team. I personally think it's fine as we're looking after enforcing order in general, not particular ordering. The current state of the things contradicts the Solidity style guide a little. Allowing users to define the weights could also be an option that would let teams follow their own rules.

## immutable-name-snakecase
Ideally this should be a part of a `naming` rule, the same way as all ordering is processed by one piece of logic. But since there is no such rule (yet?), I wouldn't merge the checks for constant and immutable variables.

👍🏻 to the rest, specifically the deprecation of `wonder-var-name-mixedcase`.

**Comment by drgorillamd** [comment]
## interface-member-order
I don't exactly recall the origin of our divergence with the style guide, I wouldn't personally be in favour of having a divergence between interface and contract tho (aka shouldn't we just drop this one @gas1cent ?)

**Comment by juanpcapurro** [comment]
> contract-data-order
> because constants and immutable variables are not stored in the state, rather
> they're a part of the contract's bytecode.

oh you're right! I had the wrong idea that immutables were present in the state
but the compiler disallowed assignments to them outside of the constructor.
Thanks for forcing me to clear that up lol

> Hence it only makes sense to declare them all together for readability reasons.

With the above in mind, I'll implement it like that, created issue #123 to track
it. If you consider it'd be a good time to also require public variables are
above private ones or something like that, let's discuss it there.


> interface-member-order
> Let me check this with the team. I personally think it's fine to change the
> rule as we're looking after enforcing order in general, not particular
> ordering. The current state of the things contradicts the Solidity style guide
> a little. 

alright, based on input from you and @drgorillamd above, I'll drop this rule.

> Allowing users to define the weights could also be an option that would let
> teams follow their own rules.

With this linter I'm inclined to make it a bit more opinionated with sane
defaults, similar to `forge fmt`, to make setting it up as simple as possible.

I'm not opposed to it though, and will implement it later down the line,
specially if there's demand for it. Added as #124, with low priority

> immutable-name-snakecase

> Ideally this should be a part of a naming rule, the same way as all ordering
> is processed by one piece of logic. But since there is no such rule (yet?), I
> wouldn't merge the checks for constant and immutable variables.

that seems reasonable, I'll keep it like it is for now

the main reasom making me reticent to implement a 'naming' rule is that
projects seem to have different conventions, especially around the use of
underscores as a sort of hungarian notation, ~and they'd want to disable just
part of the `naming` rule, which'd be awkward to do with options~.

`immutable-name-snakecase` and `constant-name-snakecase` are not controversial,
but the following are sources of contempt:

- should underscores be allowed as suffixes to a variable to avoid name
collision? the style guide says so, and is allowed in all `*-nam-mixedcase`
rules, but in this linter it has historically been disallowed for
`*-name-capwords` rules, so modifying that would be a breaking change.
- should underscores as preffixes to variables denote they're
non-external? or should they denote the variable is part of the state? the style
guide says the former, but many projects agree with the later, it being a good
way to tell apart state reads/writes when hunting for gas optimizations.

well, it might not be so nuanced after all, and it's desireable to have less rules
with simpler premises overall. created issue #125 to track it, but I'd like to
have more feedback by various projects on this before clumping all the
rules together.


thanks for your input @drgorillamd and @gas1cent
correct me if I missed something, but the only outstanding issues are with #114,
so we'll discuss it there.

After I finish implementing the changes described herein, I'll close this issue
and notify you both

Feel free to suggest anything else

**Comment by juanpcapurro** [comment]
all of the changes discussed above, plus the ones discussed in #114 are implemented and deployed in `v4.0.0-rc01`

I encourage you to semver-match against the release candidate (by setting `^4.0.0-rc01` as version in `package.json`) in the projects where you choose to use this linter, in order to get the new candidates as soon as they're published.

thanks @drgorillamd and @gas1cent for your input! I'll greatly appreciate any
feedback you have on this new version.
