### ISSUE TITLE
Define a fixer for explicit-types

### ISSUE THREAD

**Issue by juanpcapurro** [solhint-community/solhint-community#45]
in #41 I backported explicit types, however fixing issues reported by this rule should be really easy. 

Define a fixer so users don't have to do it by hand.

**Comment by dbale-altoros** [comment]
I did that last week and merged today
https://github.com/protofire/solhint/pull/504

We added tons of improvements last couple of months
Hope you can join again in [Solhint](https://github.com/protofire/solhint) repo and keep contributing as well

**Comment by juanpcapurro** [comment]
> I did that last week and merged today
> protofire/solhint#504

Hi diego, thanks for pointing me in that direction!

I'm happy that protofire/solhint is getting development time again, however the reason I started this project is to be able to provide the community with an up-to-date linter regardless of protofire's funding allocations, and dropping it to go back to work on protofire/solhint where I have no guarantee that I can push releases if the company deems the linter a not-high-enough priority in the future would defeat the purpose.

I'm looking forward to both projects coexisting and collaborating, and you're of course welcome to backport features into protofire/solhint. 
Regarding that, I expect protofire/solhint to provide proper attribution to features/bugfixes implemented in this project, either by cherry-picking commits from this repo, using the --author option in git-commit, or providing some other sort of attribution.

**Comment by dbale-altoros** [comment]
Hello!
Sorry for the late response
I understand your point
Seems like the idea here on Proto is to not let this project go to sleep again... but as I mentioned before... I get it.

Thanks for the backport offer.... the same goes for your team with the proper credits/attribution as you mention!
