### ISSUE TITLE
make sure all flags supported for files on disk also work on stdin

### ISSUE THREAD

**Issue by juanpcapurro** [solhint-community/solhint-community#73]
my idea is to remove the `stdin` subcommand and simply parse stdin if there is something on it. Perhaps printing a warning / exiting with an error code if there are also files passed as arguments.

Currently, the `stdin` subcommand is kind of a second class citizen, not allowing fixers to be run (#70) or enabling use of a non-default configuration file path.

input wanted on
- [ ] wether to remove the subcommand and trigger stdin mode if there is something on stdin
  - [ ] what to do if both stdin and filename/glob arguments are present
- [ ] what flags/options only make sense on stdin or file mode. `--filename` only makes sense on stdin mode, for example.

**Comment by 99effy** [comment]
The usual answer for whether you should specify that you're passing something from _stdin_ in any manner than simply doing it is the same as for the riddle:

> How do you get down from an elephant? **You don't.** _(You get it from a goose.)_

Having to specify a second time whether you're parsing something from stdin or not is redundant - passing input from _stdin_  to solhint by accident is extremely unlikely and in the worst case scenario you just printed a bunch of random stuff or got solhint to throw an error.
